// Generated by CoffeeScript 1.7.1
(function() {
  describe("Individual", function() {
    describe("initialized without params", function() {
      var individual;
      individual = new Individual();
      it("should be initialized as random binary array", function() {
        return expect(individual.genome).toMatch(1, 0);
      });
      return it("should have a length of 10", function() {
        return expect(individual.genome.length).toEqual(10);
      });
    });
    return describe("initialized with params", function() {
      it("should have the right genome", function() {
        var genome, individual;
        genome = [
          {
            1: 1,
            2: 2
          }, {
            1: 1,
            2: 2
          }, {
            1: 1,
            4: 4
          }
        ];
        individual = new Individual({
          genome: genome
        });
        return expect(individual.genome).toEqual(genome);
      });
      it("should have the right length", function() {
        var individual, length;
        length = 20;
        individual = new Individual({
          length: length
        });
        return expect(individual.length).toEqual(length);
      });
      return it("should have the right permutations", function() {
        var alleles, individual;
        alleles = ["a", "b", "c"];
        individual = new Individual({
          alleles: alleles
        });
        return expect(individual.alleles).toEqual(alleles);
      });
    });
  });

}).call(this);

//# sourceMappingURL=IndividualSpec.map
