// Generated by CoffeeScript 1.7.1
(function() {
  describe("Mutation", function() {
    var individual;
    individual = void 0;
    beforeEach(function() {
      return individual = new Individual();
    });
    describe("bitFlip() mutation", function() {
      var bitFlip;
      bitFlip = void 0;
      beforeEach(function() {
        return bitFlip = Mutation.bitFlip(individual.genome);
      });
      return it("should return a genome of the correct length", function() {
        return expect(bitFlip.length).toEqual(individual.genome.length);
      });
    });
    return describe("inverse() mutation", function() {
      var inverse;
      inverse = void 0;
      beforeEach(function() {
        return inverse = Mutation.inverse(individual.genome);
      });
      return it("should return a genome of the correct length", function() {
        return expect(inverse.length).toEqual(individual.genome.length);
      });
    });
  });

}).call(this);

//# sourceMappingURL=MutationSpec.map
