// Generated by CoffeeScript 1.7.1
(function() {
  var Individual;

  Individual = (function() {
    function Individual(args) {
      var _ref, _ref1, _ref2;
      if (args == null) {
        args = {};
      }
      this.length = (_ref = args.length) != null ? _ref : 10;
      this.alleles = (_ref1 = args.alleles) != null ? _ref1 : [1, 0];
      this._genome = (_ref2 = args.genome) != null ? _ref2 : this.initialize();
    }

    Object.defineProperties(Individual.prototype, {
      genome: {
        get: function() {
          return this._genome.slice();
        },
        set: function(genome) {
          return this._genome = genome;
        }
      }
    });

    Individual.prototype.initialize = function() {
      var i, _i, _ref, _results;
      _results = [];
      for (i = _i = 1, _ref = this.length; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
        _results.push(this.alleles[Math.floor(Math.random() * this.alleles.length)]);
      }
      return _results;
    };

    return Individual;

  })();

  this.Individual = Individual;

}).call(this);

//# sourceMappingURL=Individual.map
